### ISSUE TITLE
whip connection does not work

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [livekit/ingress#231]
I'm trying to use WHIP instead of RTMP (RTMP works fine) but after accepting the connection the connection drops.

![image](https://github.com/livekit/ingress/assets/154023155/69fd4bc8-039d-4cfe-8c3a-1c96a2287b89)

**Config**
```yaml
logging:
  level: debug
redis:
    address: localhost:6379
api_key: *******
api_secret: *******
ws_url: wss://MY.URL
rtmp_port: 1935
whip_port: 8080
http_relay_port: 9090

rtc_config:
  tcp_port: 7882 # 7881 - already in use
  udp_port: 7885
  use_external_ip: false

```
